### ISSUE TITLE
WordPress Multisite

### ISSUE THREAD

**Issue by foodnavorg** [mattweber/solr-for-wordpress#1]
Is there any particular reason why you haven't worked to convert this to MultiSite?  Or for that matter to being used in the newer versions of WordPress?  It doesn't seem all that difficult to just change the is_wpmu() to is_multisite()?  Am I missing something bigger here?

I'm not sure I want to just index "my" content and since that part seemed to be the hardest part of doing a multisite search I had also already looked into using Nutch to crawl and index everything.  If that's the case and the Index already exists where could I just use the Search Form portion of this plugin to display the Search results from Solr?

I'm running CentOS on the box I set up for this and my libxml2 is a like 2 versions back from what php.net suggests as the minimum is the whole thing going to crash if I try to do the work on this to update it?

And I'm new to github and colaborative development completely so I'm not sure how to even start this here or do I just do it all myself?  I'd love to include it as part of the project here as a decent Search functionality is Seriously lacking in WordPress Multisite.

Thanks,

Jerry Craig
Cupbearer

**Comment by mattweber** [comment]
Multisite support was added in 0.4.0.

**Comment by foodnavorg** [comment]
Awesome, I had just been messing with it and was almost done, but I'm sure yours is way better and prettier.

Jerry E. Craig, Jr.
Direct: 480-304-7123 or 866-694-6998
www.inforeverse.com

-----Original Message-----
