### ISSUE TITLE
word1 word2 in a post become word1word2 in the index 

### ISSUE THREAD

**Issue by bejean** [mattweber/solr-for-wordpress#11]
If the post contains something like

word1&lt;/h4&gt;

&lt;p&gt;word2

strip_tags($post_info->post_content) converts this in

word1\r\n\r\n\r\nword2

then in Service.php, $rawPost .= $this->_documentToXmlFragment($document); converts this in

word1word2 

due to the line

$value = preg_replace('/\pC/u', '', $value); // remove unicode Control chars.

so searching word1 do not return the document and the speelcheking suggests "word1word2"

the issue is in  solr-php-client, but it should be workarounded in s4w_build_document with

$doc->setField( 'content', preg_replace('/\r\n/', ' ', strip_tags($post_info->post_content)) );

**Comment by shaksi** [comment]
hmm interesting, any ideas how we could tackle this/

**Comment by bejean** [comment]
This is fixed in 
http://code.google.com/p/solr-php-client/downloads/detail?name=SolrPhpClient.r60.2011-05-04.zip

**Comment by shaksi** [comment]
heh yes it would help if we kept our SolrPhpClient upto date.
Thanks for that will read up on the changes, hopefully the updates do not break anything

**Comment by bejean** [comment]
I installed it on my own blog and it looks good.

**Comment by shaksi** [comment]
Okay that seems to solve the problem, and can confirm search is similarly intact

**Comment by bejean** [comment]
Works for me too !

Can be close.
