### ISSUE TITLE
Release 0.5.0 to Wordpress Plugin Site

### ISSUE THREAD

**Issue by mattweber** [mattweber/solr-for-wordpress#22]
Everyone, thanks for all the work you have been doing on the plugin.  WIth all these changes I think it would be a good time to push out a 0.5.0 version to the Wordpress Plugin site.  Please test the latest version of the master branch and let me know if you have any issues.  If not I will push out a 0.5.0 version in the next week or so.

Thanks,
Matt Weber

**Comment by shaksi** [comment]
Yes its looking good with a lot of multisite update. 
Once this release goes out it might be worth opening a pad/gist and listing things one would like to see in the next release.

**Comment by shaksi** [comment]
@mattweber 
Unless there is something unbeknownst to me, I think we are at a good place to do a 0.5.0 release.
I have done a 0.5.0 tag release

I have tested the plugin with Solr 1.4.1 and 3.5.0 using WP 3.2 and 3.3 and it works fine.

There are some deprecated tokenizers in the schema.xml but i dont think we should remove them atm.

**Comment by mattweber** [comment]
I agree.  I will push one out.

**Comment by mattweber** [comment]
Pushed pushed out 0.5.1 to Wordpress plugin site as well.
