### ISSUE TITLE
Hierarchical custom taxonomy

### ISSUE THREAD

**Issue by alxvallejo** [mattweber/solr-for-wordpress#35]
I've successfully index my custom taxonomy terms but they are not hierarchical like the categories field. I'm working on a fix but if anyone has a solution, let me know.

**Comment by mattweber** [comment]
Yea, taxonomy is only supported for categories.  You can define a field like categories, do the same indexing logic, then look at the code starting at line 788 of solr-for-wordpress.php so see how to display it in the UI.
