### ISSUE TITLE
Unable to configure in WP 3.3.1

### ISSUE THREAD

**Issue by kodo65** [mattweber/solr-for-wordpress#44]
Hi!

I installed a fresh version of WP, version 3.3.1, and then installed the latest Solr for Wordpress plug-in but when I try to save the settings I get a "You do not have sufficient permissions to access this page." error. I use the "Single Server" mode. I first ran into this problem trying to install it on my Debian VPS but I get exactly the same error using my WAMP/Bitnami stack...

Any ideas of what's wrong here?

Many thanks!
Peter

**Comment by dustinrue** [comment]
Are you logged in as your site's administrator or a user with full administrator privs?

**Comment by kodo65** [comment]
Hi!

Finally I managed to get the plug-in to work on my VPS. I downloaded the 0.5.1 version from wordpress.org and then updated:
- solr-for-wordpress.php
- solr-options-page.php
- schema.xml
  from github and now it works. Great!!!!

Looks really great! Good work:)
/Peter
